services:
  agent:
    image: bootcamp/gocd-agent

    environment:
      - GO_SERVER_URL=http://10.132.125.60:8153/go
      - AGENT_AUTO_REGISTER_KEY=cb757faf-415f-48dd-95d2-8d2829590912

    volumes:
      - ./scripts/agent:/docker-entrypoint.d
      - ./scripts/shared:/shared

    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 4G
        reservations:
          cpus: '0.0001'
          memory: 500M
